CREATE TABLE animal (
                        id          bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name        varchar(255)  NOT NULL,
                        species     varchar(255)  NOT NULL,
                        breed       varchar(255)  NOT NULL,
                        intake_date date          NOT NULL,
                        status      varchar(255)  NOT NULL
);

CREATE TABLE adopter (
                        id    bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name  varchar(255) NOT NULL,
                        email varchar(255)
);

CREATE TABLE caretaker (
                        id             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name           varchar(255) NOT NULL,
                        email          varchar(255),
                        specialization varchar(255) NOT NULL
);

CREATE TABLE medical_record (
                        id             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        animal_id      bigint       NOT NULL REFERENCES animal(id),
                        description    varchar(255) NOT NULL,
                        treatment_date date         NOT NULL,
                        vet_name       varchar(255) NOT NULL
);

CREATE TABLE adoption (
                        id         bigint PRIMARY KEY REFERENCES animal(id),
                        date       date   NOT NULL,
                        adopter_id bigint REFERENCES adopter(id)
);

CREATE TABLE animal_caretaker (
                        animal_id    bigint NOT NULL REFERENCES animal(id),
                        caretaker_id bigint NOT NULL REFERENCES caretaker(id),
                        PRIMARY KEY (animal_id, caretaker_id)
);
