CREATE TABLE account (
                         id          bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username    varchar(255)  NOT NULL UNIQUE,
                         password    varchar(255)  NOT NULL,
                         email       varchar(255)  NOT NULL,
                         role        varchar(255)  NOT NULL
);