CREATE TABLE outbox (
                        id                  bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        aggregate_type      varchar(255)    NOT NULL,
                        aggregate_id        varchar(255)    NOT NULL,
                        event_type          varchar(255)    NOT NULL,
                        payload             jsonb           NOT NULL,
                        created_at          timestamptz     NOT NULL DEFAULT now(),
                        published_at        timestamptz
);
CREATE INDEX idx_outbox_unpublished ON outbox (created_at) WHERE published_at IS NULL;